"""protocol_number column

Revision ID: 89f3c7c8587e
Revises: fb7f3c8fa601
Create Date: 2024-12-17 10:37:02.782951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89f3c7c8587e"
down_revision: Union[str, None] = "fb7f3c8fa601"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personal_naks_certification_table",
        sa.Column("protocol_number", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("personal_naks_certification_table", "protocol_number")
    # ### end Alembic commands ###
