"""init

Revision ID: 9139ebd373d2
Revises: 
Create Date: 2024-10-18 16:00:00.675374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9139ebd373d2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("kleymo", sa.String(length=4), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("passport_number", sa.String(), nullable=True),
        sa.Column("exp_age", sa.Integer(), nullable=True),
        sa.Column("nation", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("ident"),
        sa.UniqueConstraint("kleymo"),
    )
    op.create_index("name_idx", "personal_table", ["name"], unique=False)
    op.create_index(
        "personal_ident_idx", "personal_table", ["ident"], unique=False
    )
    op.create_index(
        "personal_kleymo_idx", "personal_table", ["kleymo"], unique=False
    )
    op.create_table(
        "ndt_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("personal_ident", sa.UUID(), nullable=False),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("subcompany", sa.String(), nullable=True),
        sa.Column("project", sa.String(), nullable=True),
        sa.Column("welding_date", sa.Date(), nullable=False),
        sa.Column("ndt_type", sa.String(), nullable=False),
        sa.Column("total_welded", sa.Float(), nullable=False),
        sa.Column("total_ndt", sa.Float(), nullable=False),
        sa.Column("total_accepted", sa.Float(), nullable=False),
        sa.Column("total_rejected", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["personal_ident"],
            ["personal_table.ident"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ident"),
        sa.UniqueConstraint(
            "personal_ident",
            "company",
            "subcompany",
            "project",
            "welding_date",
            "ndt_type",
        ),
    )
    op.create_index("ndt_ident_idx", "ndt_table", ["ident"], unique=False)
    op.create_index(
        "ndt_welding_date_idx", "ndt_table", ["welding_date"], unique=False
    )
    op.create_index(
        "total_accepted_idx", "ndt_table", ["total_accepted"], unique=False
    )
    op.create_index("total_ndt_idx", "ndt_table", ["total_ndt"], unique=False)
    op.create_index(
        "total_rejectedidx", "ndt_table", ["total_rejected"], unique=False
    )
    op.create_index(
        "total_welded_idx", "ndt_table", ["total_welded"], unique=False
    )
    op.create_table(
        "personal_naks_certification_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("personal_ident", sa.UUID(), nullable=False),
        sa.Column("job_title", sa.String(), nullable=False),
        sa.Column("certification_number", sa.String(), nullable=False),
        sa.Column("certification_date", sa.Date(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("expiration_date_fact", sa.Date(), nullable=False),
        sa.Column("insert", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("gtd", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("details_type", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("joint_type", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "welding_materials_groups", sa.ARRAY(sa.String()), nullable=True
        ),
        sa.Column("details_thikness_from", sa.Float(), nullable=True),
        sa.Column("details_thikness_before", sa.Float(), nullable=True),
        sa.Column("outer_diameter_from", sa.Float(), nullable=True),
        sa.Column("outer_diameter_before", sa.Float(), nullable=True),
        sa.Column("welding_position", sa.String(), nullable=True),
        sa.Column("connection_type", sa.String(), nullable=True),
        sa.Column("rod_diameter_from", sa.Float(), nullable=True),
        sa.Column("rod_diameter_before", sa.Float(), nullable=True),
        sa.Column("rod_axis_position", sa.String(), nullable=True),
        sa.Column("details_diameter_from", sa.Float(), nullable=True),
        sa.Column("details_diameter_before", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["personal_ident"],
            ["personal_table.ident"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ident"),
        sa.UniqueConstraint(
            "certification_number",
            "certification_date",
            "expiration_date_fact",
            "insert",
        ),
    )
    op.create_index(
        "certification_idx",
        "personal_naks_certification_table",
        ["certification_number", "certification_date", "expiration_date_fact"],
        unique=False,
    )
    op.create_index(
        "certification_personal_ident_idx",
        "personal_naks_certification_table",
        ["personal_ident"],
        unique=False,
    )
    op.create_index(
        "details_thikness_before_idx",
        "personal_naks_certification_table",
        ["details_thikness_before"],
        unique=False,
    )
    op.create_index(
        "details_thikness_from_idx",
        "personal_naks_certification_table",
        ["details_thikness_from"],
        unique=False,
    )
    op.create_index(
        "gtd_idx", "personal_naks_certification_table", ["gtd"], unique=False
    )
    op.create_index(
        "method_idx",
        "personal_naks_certification_table",
        ["method"],
        unique=False,
    )
    op.create_index(
        "outer_diameter_before_idx",
        "personal_naks_certification_table",
        ["outer_diameter_before"],
        unique=False,
    )
    op.create_index(
        "outer_diameter_from_idx",
        "personal_naks_certification_table",
        ["outer_diameter_from"],
        unique=False,
    )
    op.create_index(
        "personal_certification_ident_idx",
        "personal_naks_certification_table",
        ["ident"],
        unique=False,
    )
    op.create_index(
        "rod_diameter_before_idx",
        "personal_naks_certification_table",
        ["rod_diameter_before"],
        unique=False,
    )
    op.create_index(
        "rod_diameter_from_idx",
        "personal_naks_certification_table",
        ["rod_diameter_from"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "rod_diameter_from_idx", table_name="personal_naks_certification_table"
    )
    op.drop_index(
        "rod_diameter_before_idx",
        table_name="personal_naks_certification_table",
    )
    op.drop_index(
        "personal_certification_ident_idx",
        table_name="personal_naks_certification_table",
    )
    op.drop_index(
        "outer_diameter_from_idx",
        table_name="personal_naks_certification_table",
    )
    op.drop_index(
        "outer_diameter_before_idx",
        table_name="personal_naks_certification_table",
    )
    op.drop_index("method_idx", table_name="personal_naks_certification_table")
    op.drop_index("gtd_idx", table_name="personal_naks_certification_table")
    op.drop_index(
        "details_thikness_from_idx",
        table_name="personal_naks_certification_table",
    )
    op.drop_index(
        "details_thikness_before_idx",
        table_name="personal_naks_certification_table",
    )
    op.drop_index(
        "certification_personal_ident_idx",
        table_name="personal_naks_certification_table",
    )
    op.drop_index(
        "certification_idx", table_name="personal_naks_certification_table"
    )
    op.drop_table("personal_naks_certification_table")
    op.drop_index("total_welded_idx", table_name="ndt_table")
    op.drop_index("total_rejectedidx", table_name="ndt_table")
    op.drop_index("total_ndt_idx", table_name="ndt_table")
    op.drop_index("total_accepted_idx", table_name="ndt_table")
    op.drop_index("ndt_welding_date_idx", table_name="ndt_table")
    op.drop_index("ndt_ident_idx", table_name="ndt_table")
    op.drop_table("ndt_table")
    op.drop_index("personal_kleymo_idx", table_name="personal_table")
    op.drop_index("personal_ident_idx", table_name="personal_table")
    op.drop_index("name_idx", table_name="personal_table")
    op.drop_table("personal_table")
    # ### end Alembic commands ###
