"""personal_naks_certification_table update

Revision ID: ade3188eeef1
Revises: 9139ebd373d2
Create Date: 2024-11-07 17:20:13.180910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ade3188eeef1"
down_revision: Union[str, None] = "9139ebd373d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personal_naks_certification_table",
        sa.Column("detail_types", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column("joint_types", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column("materials", sa.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column("detail_thikness_from", sa.Float(), nullable=True),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column("detail_thikness_before", sa.Float(), nullable=True),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column("detail_diameter_from", sa.Float(), nullable=True),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column("detail_diameter_before", sa.Float(), nullable=True),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column("html", sa.String(), nullable=False),
    )
    op.drop_index(
        "details_thikness_before_idx",
        table_name="personal_naks_certification_table",
    )
    op.create_index(
        "details_thikness_before_idx",
        "personal_naks_certification_table",
        ["detail_thikness_before"],
        unique=False,
    )
    op.drop_index(
        "details_thikness_from_idx",
        table_name="personal_naks_certification_table",
    )
    op.create_index(
        "details_thikness_from_idx",
        "personal_naks_certification_table",
        ["detail_thikness_from"],
        unique=False,
    )
    op.drop_column("personal_naks_certification_table", "welding_position")
    op.drop_column(
        "personal_naks_certification_table", "welding_materials_groups"
    )
    op.drop_column("personal_naks_certification_table", "job_title")
    op.drop_column("personal_naks_certification_table", "joint_type")
    op.drop_column("personal_naks_certification_table", "details_type")
    op.drop_column(
        "personal_naks_certification_table", "details_diameter_before"
    )
    op.drop_column(
        "personal_naks_certification_table", "details_thikness_from"
    )
    op.drop_column(
        "personal_naks_certification_table", "details_diameter_from"
    )
    op.drop_column("personal_naks_certification_table", "connection_type")
    op.drop_column("personal_naks_certification_table", "rod_axis_position")
    op.drop_column(
        "personal_naks_certification_table", "details_thikness_before"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "details_thikness_before",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "rod_axis_position",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "connection_type", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "details_diameter_from",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "details_thikness_from",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "details_diameter_before",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "details_type",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "joint_type",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "job_title", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "welding_materials_groups",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personal_naks_certification_table",
        sa.Column(
            "welding_position",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        "details_thikness_from_idx",
        table_name="personal_naks_certification_table",
    )
    op.create_index(
        "details_thikness_from_idx",
        "personal_naks_certification_table",
        ["details_thikness_from"],
        unique=False,
    )
    op.drop_index(
        "details_thikness_before_idx",
        table_name="personal_naks_certification_table",
    )
    op.create_index(
        "details_thikness_before_idx",
        "personal_naks_certification_table",
        ["details_thikness_before"],
        unique=False,
    )
    op.drop_column("personal_naks_certification_table", "html")
    op.drop_column(
        "personal_naks_certification_table", "detail_diameter_before"
    )
    op.drop_column("personal_naks_certification_table", "detail_diameter_from")
    op.drop_column(
        "personal_naks_certification_table", "detail_thikness_before"
    )
    op.drop_column("personal_naks_certification_table", "detail_thikness_from")
    op.drop_column("personal_naks_certification_table", "materials")
    op.drop_column("personal_naks_certification_table", "joint_types")
    op.drop_column("personal_naks_certification_table", "detail_types")
    # ### end Alembic commands ###
