"""acst preheating and heat treatment columns removed

Revision ID: ecb64df11fdc
Revises: 4628494c9cde
Create Date: 2024-11-19 11:55:31.685255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ecb64df11fdc"
down_revision: Union[str, None] = "4628494c9cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("acst_table", "heat_treatment")
    op.drop_column("acst_table", "preheating")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "acst_table",
        sa.Column(
            "preheating", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "acst_table",
        sa.Column(
            "heat_treatment", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
