"""acst preheating and heat treatment columns recreate

Revision ID: fb7f3c8fa601
Revises: ecb64df11fdc
Create Date: 2024-11-19 11:56:10.879289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb7f3c8fa601"
down_revision: Union[str, None] = "ecb64df11fdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "acst_table",
        sa.Column("preheating", sa.ARRAY(sa.BOOLEAN()), nullable=True),
    )
    op.add_column(
        "acst_table",
        sa.Column("heat_treatment", sa.ARRAY(sa.BOOLEAN()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("acst_table", "heat_treatment")
    op.drop_column("acst_table", "preheating")
    # ### end Alembic commands ###
