"""init migration

Revision ID: 002f044afddf
Revises: 
Create Date: 2024-06-11 15:37:04.665090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "002f044afddf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("sign_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.Column("login_date", sa.DateTime(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("ident"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "welder_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("kleymo", sa.String(length=4), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("sicil", sa.String(), nullable=True),
        sa.Column("passport_number", sa.String(), nullable=True),
        sa.Column("nation", sa.String(), nullable=True),
        sa.Column("status", sa.SMALLINT(), nullable=True),
        sa.PrimaryKeyConstraint("ident"),
        sa.UniqueConstraint("kleymo"),
    )
    op.create_table(
        "ndt_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("kleymo", sa.String(length=4), nullable=False),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("subcompany", sa.String(), nullable=True),
        sa.Column("project", sa.String(), nullable=True),
        sa.Column("welding_date", sa.Date(), nullable=False),
        sa.Column("ndt_type", sa.String(), nullable=True),
        sa.Column("total_welded", sa.Float(), nullable=False),
        sa.Column("total_ndt", sa.Float(), nullable=False),
        sa.Column("accepted", sa.Float(), nullable=False),
        sa.Column("rejected", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kleymo"],
            ["welder_table.kleymo"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ident"),
    )
    op.create_table(
        "refresh_token_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("user_ident", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("exp_dt", sa.DateTime(), nullable=False),
        sa.Column("gen_dt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_ident"],
            ["user_table.ident"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ident"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "welder_certification_table",
        sa.Column("ident", sa.UUID(), nullable=False),
        sa.Column("kleymo", sa.String(length=4), nullable=False),
        sa.Column("job_title", sa.String(), nullable=True),
        sa.Column("certification_number", sa.String(), nullable=False),
        sa.Column("certification_date", sa.Date(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("expiration_date_fact", sa.Date(), nullable=False),
        sa.Column("insert", sa.String(), nullable=True),
        sa.Column("certification_type", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("gtd", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("details_type", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("joint_type", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "welding_materials_groups", sa.ARRAY(sa.String()), nullable=True
        ),
        sa.Column("welding_materials", sa.String(), nullable=True),
        sa.Column("details_thikness_from", sa.Float(), nullable=True),
        sa.Column("details_thikness_before", sa.Float(), nullable=True),
        sa.Column("outer_diameter_from", sa.Float(), nullable=True),
        sa.Column("outer_diameter_before", sa.Float(), nullable=True),
        sa.Column("welding_position", sa.String(), nullable=True),
        sa.Column("connection_type", sa.String(), nullable=True),
        sa.Column("rod_diameter_from", sa.Float(), nullable=True),
        sa.Column("rod_diameter_before", sa.Float(), nullable=True),
        sa.Column("rod_axis_position", sa.String(), nullable=True),
        sa.Column("weld_type", sa.String(), nullable=True),
        sa.Column("joint_layer", sa.String(), nullable=True),
        sa.Column("sdr", sa.String(), nullable=True),
        sa.Column("automation_level", sa.String(), nullable=True),
        sa.Column("details_diameter_from", sa.Float(), nullable=True),
        sa.Column("details_diameter_before", sa.Float(), nullable=True),
        sa.Column("welding_equipment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["kleymo"],
            ["welder_table.kleymo"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ident"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("welder_certification_table")
    op.drop_table("refresh_token_table")
    op.drop_table("ndt_table")
    op.drop_table("welder_table")
    op.drop_table("user_table")
    # ### end Alembic commands ###
