"""init migration

Revision ID: 5e0edef9ad54
Revises: 
Create Date: 2024-06-28 13:17:11.142267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e0edef9ad54"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ndt_table",
        "total_welded",
        existing_type=sa.REAL(),
        server_default=None,
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "ndt_table",
        "total_ndt",
        existing_type=sa.REAL(),
        server_default=None,
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "ndt_table",
        "accepted",
        existing_type=sa.REAL(),
        server_default=None,
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "ndt_table",
        "rejected",
        existing_type=sa.REAL(),
        server_default=None,
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.create_index("accepted_idx", "ndt_table", ["accepted"], unique=False)
    op.create_index("ndt_ident_idx", "ndt_table", ["ident"], unique=False)
    op.create_index(
        "ndt_idx",
        "ndt_table",
        ["kleymo", "company", "subcompany", "project"],
        unique=False,
    )
    op.create_index("rejected_idx", "ndt_table", ["rejected"], unique=False)
    op.create_index("total_ndt_idx", "ndt_table", ["total_ndt"], unique=False)
    op.create_index(
        "total_welded_idx", "ndt_table", ["total_welded"], unique=False
    )
    op.create_unique_constraint(
        None,
        "ndt_table",
        [
            "kleymo",
            "company",
            "subcompany",
            "project",
            "welding_date",
            "ndt_type",
        ],
    )
    op.drop_constraint("welder_fk", "ndt_table", type_="foreignkey")
    op.create_foreign_key(
        None,
        "ndt_table",
        "welder_table",
        ["kleymo"],
        ["kleymo"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "welder_certification_table",
        "kleymo",
        existing_type=sa.CHAR(length=4),
        type_=sa.String(length=4),
        existing_nullable=False,
    )
    op.alter_column(
        "welder_certification_table",
        "details_thikness_from",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "details_thikness_before",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "outer_diameter_from",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "outer_diameter_before",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "rod_diameter_from",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "rod_diameter_before",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "details_diameter_from",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "details_diameter_before",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.drop_constraint(
        "certification_id", "welder_certification_table", type_="unique"
    )
    op.drop_index("fki_welder", table_name="welder_certification_table")
    op.drop_index(
        "idx_welder_certification_certification_date",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_certification_number",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_details_diameter_before",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_details_diameter_from",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_details_thikness_before",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_details_thikness_from",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_expiration_date",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_expiration_date_fact",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_kleymo",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_outer_diameter_before",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_outer_diameter_from",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_rod_diameter_before",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "idx_welder_certification_rod_diameter_from",
        table_name="welder_certification_table",
    )
    op.create_index(
        "certification_idx",
        "welder_certification_table",
        ["certification_number", "certification_date", "expiration_date_fact"],
        unique=False,
    )
    op.create_index(
        "details_thikness_before_idx",
        "welder_certification_table",
        ["details_thikness_before"],
        unique=False,
    )
    op.create_index(
        "details_thikness_from_idx",
        "welder_certification_table",
        ["details_thikness_from"],
        unique=False,
    )
    op.create_index(
        "gtd_idx", "welder_certification_table", ["gtd"], unique=False
    )
    op.create_index(
        "method_idx", "welder_certification_table", ["method"], unique=False
    )
    op.create_index(
        "outer_diameter_before_idx",
        "welder_certification_table",
        ["outer_diameter_before"],
        unique=False,
    )
    op.create_index(
        "outer_diameter_from_idx",
        "welder_certification_table",
        ["outer_diameter_from"],
        unique=False,
    )
    op.create_index(
        "rod_diameter_before_idx",
        "welder_certification_table",
        ["rod_diameter_before"],
        unique=False,
    )
    op.create_index(
        "rod_diameter_from_idx",
        "welder_certification_table",
        ["rod_diameter_from"],
        unique=False,
    )
    op.create_index(
        "welder_certification_ident_idx",
        "welder_certification_table",
        ["ident"],
        unique=False,
    )
    op.create_index(
        "welder_certification_kleymo_idx",
        "welder_certification_table",
        ["kleymo"],
        unique=False,
    )
    op.create_unique_constraint(
        None,
        "welder_certification_table",
        [
            "kleymo",
            "certification_number",
            "certification_date",
            "expiration_date_fact",
            "insert",
        ],
    )
    op.drop_column("welder_certification_table", "certification_id")
    op.alter_column(
        "welder_table",
        "kleymo",
        existing_type=sa.CHAR(length=4),
        type_=sa.String(length=4),
        nullable=True,
    )
    op.drop_index("idx_welder_table_kleymo", table_name="welder_table")
    op.drop_index("idx_welder_table_name", table_name="welder_table")
    op.create_index("name_idx", "welder_table", ["name"], unique=False)
    op.create_index(
        "welder_ident_idx", "welder_table", ["ident"], unique=False
    )
    op.create_index(
        "welder_kleymo_idx", "welder_table", ["kleymo"], unique=False
    )
    op.drop_column("welder_table", "passport_issue_place")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "welder_table",
        sa.Column(
            "passport_issue_place",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index("welder_kleymo_idx", table_name="welder_table")
    op.drop_index("welder_ident_idx", table_name="welder_table")
    op.drop_index("name_idx", table_name="welder_table")
    op.create_index(
        "idx_welder_table_name", "welder_table", ["name"], unique=False
    )
    op.create_index(
        "idx_welder_table_kleymo", "welder_table", ["kleymo"], unique=False
    )
    op.alter_column(
        "welder_table",
        "kleymo",
        existing_type=sa.String(length=4),
        type_=sa.CHAR(length=4),
        nullable=False,
    )
    op.add_column(
        "welder_certification_table",
        sa.Column(
            "certification_id",
            sa.VARCHAR(),
            server_default=sa.text("'fefrfr'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "welder_certification_table", type_="unique")
    op.drop_index(
        "welder_certification_kleymo_idx",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "welder_certification_ident_idx",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "rod_diameter_from_idx", table_name="welder_certification_table"
    )
    op.drop_index(
        "rod_diameter_before_idx", table_name="welder_certification_table"
    )
    op.drop_index(
        "outer_diameter_from_idx", table_name="welder_certification_table"
    )
    op.drop_index(
        "outer_diameter_before_idx", table_name="welder_certification_table"
    )
    op.drop_index("method_idx", table_name="welder_certification_table")
    op.drop_index("gtd_idx", table_name="welder_certification_table")
    op.drop_index(
        "details_thikness_from_idx", table_name="welder_certification_table"
    )
    op.drop_index(
        "details_thikness_before_idx", table_name="welder_certification_table"
    )
    op.drop_index("certification_idx", table_name="welder_certification_table")
    op.create_index(
        "idx_welder_certification_rod_diameter_from",
        "welder_certification_table",
        ["rod_diameter_from"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_rod_diameter_before",
        "welder_certification_table",
        ["rod_diameter_before"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_outer_diameter_from",
        "welder_certification_table",
        ["outer_diameter_from"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_outer_diameter_before",
        "welder_certification_table",
        ["outer_diameter_before"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_kleymo",
        "welder_certification_table",
        ["kleymo"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_expiration_date_fact",
        "welder_certification_table",
        ["expiration_date_fact"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_expiration_date",
        "welder_certification_table",
        ["expiration_date"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_details_thikness_from",
        "welder_certification_table",
        ["details_thikness_from"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_details_thikness_before",
        "welder_certification_table",
        ["details_thikness_before"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_details_diameter_from",
        "welder_certification_table",
        ["details_diameter_from"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_details_diameter_before",
        "welder_certification_table",
        ["details_diameter_before"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_certification_number",
        "welder_certification_table",
        ["certification_number"],
        unique=False,
    )
    op.create_index(
        "idx_welder_certification_certification_date",
        "welder_certification_table",
        ["certification_date"],
        unique=False,
    )
    op.create_index(
        "fki_welder", "welder_certification_table", ["kleymo"], unique=False
    )
    op.create_unique_constraint(
        "certification_id",
        "welder_certification_table",
        [
            "certification_number",
            "certification_date",
            "expiration_date_fact",
            "insert",
        ],
    )
    op.alter_column(
        "welder_certification_table",
        "details_diameter_before",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "details_diameter_from",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "rod_diameter_before",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "rod_diameter_from",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "outer_diameter_before",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "outer_diameter_from",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "details_thikness_before",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "details_thikness_from",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "welder_certification_table",
        "kleymo",
        existing_type=sa.String(length=4),
        type_=sa.CHAR(length=4),
        existing_nullable=False,
    )
    op.drop_constraint(None, "ndt_table", type_="foreignkey")
    op.create_foreign_key(
        "welder_fk", "ndt_table", "welder_table", ["kleymo"], ["kleymo"]
    )
    op.drop_constraint(None, "ndt_table", type_="unique")
    op.drop_index("total_welded_idx", table_name="ndt_table")
    op.drop_index("total_ndt_idx", table_name="ndt_table")
    op.drop_index("rejected_idx", table_name="ndt_table")
    op.drop_index("ndt_idx", table_name="ndt_table")
    op.drop_index("ndt_ident_idx", table_name="ndt_table")
    op.drop_index("accepted_idx", table_name="ndt_table")
    op.alter_column(
        "ndt_table",
        "rejected",
        existing_type=sa.Float(),
        server_default=sa.text("0"),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "ndt_table",
        "accepted",
        existing_type=sa.Float(),
        server_default=sa.text("0"),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "ndt_table",
        "total_ndt",
        existing_type=sa.Float(),
        server_default=sa.text("0"),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "ndt_table",
        "total_welded",
        existing_type=sa.Float(),
        server_default=sa.text("0"),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
