"""create indexes and constraits

Revision ID: 90b777baaddf
Revises: 002f044afddf
Create Date: 2024-06-11 16:04:07.446868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90b777baaddf"
down_revision: Union[str, None] = "002f044afddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("accepted_idx", "ndt_table", ["accepted"], unique=False)
    op.create_index("ndt_ident_idx", "ndt_table", ["ident"], unique=False)
    op.create_index(
        "ndt_idx",
        "ndt_table",
        ["kleymo", "company", "subcompany", "project"],
        unique=False,
    )
    op.create_index("rejected_idx", "ndt_table", ["rejected"], unique=False)
    op.create_index("total_ndt_idx", "ndt_table", ["total_ndt"], unique=False)
    op.create_index(
        "total_welded_idx", "ndt_table", ["total_welded"], unique=False
    )
    op.create_unique_constraint(
        None,
        "ndt_table",
        [
            "kleymo",
            "company",
            "subcompany",
            "project",
            "welding_date",
            "ndt_type",
        ],
    )
    op.create_index(
        "refresh_token_ident_idx",
        "refresh_token_table",
        ["ident"],
        unique=False,
    )
    op.create_index(
        "revoked_idx", "refresh_token_table", ["revoked"], unique=False
    )
    op.create_index(
        "token_idx", "refresh_token_table", ["token"], unique=False
    )
    op.create_index("user_ident_idx", "user_table", ["ident"], unique=False)
    op.create_index(
        "certification_idx",
        "welder_certification_table",
        ["certification_number", "certification_date", "expiration_date_fact"],
        unique=False,
    )
    op.create_index(
        "details_thikness_before_idx",
        "welder_certification_table",
        ["details_thikness_before"],
        unique=False,
    )
    op.create_index(
        "details_thikness_from_idx",
        "welder_certification_table",
        ["details_thikness_from"],
        unique=False,
    )
    op.create_index(
        "gtd_idx", "welder_certification_table", ["gtd"], unique=False
    )
    op.create_index(
        "method_idx", "welder_certification_table", ["method"], unique=False
    )
    op.create_index(
        "outer_diameter_before_idx",
        "welder_certification_table",
        ["outer_diameter_before"],
        unique=False,
    )
    op.create_index(
        "outer_diameter_from_idx",
        "welder_certification_table",
        ["outer_diameter_from"],
        unique=False,
    )
    op.create_index(
        "rod_diameter_before_idx",
        "welder_certification_table",
        ["rod_diameter_before"],
        unique=False,
    )
    op.create_index(
        "rod_diameter_from_idx",
        "welder_certification_table",
        ["rod_diameter_from"],
        unique=False,
    )
    op.create_index(
        "welder_certification_ident_idx",
        "welder_certification_table",
        ["ident"],
        unique=False,
    )
    op.create_index(
        "welder_certification_kleymo_idx",
        "welder_certification_table",
        ["kleymo"],
        unique=False,
    )
    op.create_unique_constraint(
        None,
        "welder_certification_table",
        [
            "kleymo",
            "certification_number",
            "certification_date",
            "expiration_date_fact",
            "insert",
        ],
    )
    op.create_index("name_idx", "welder_table", ["name"], unique=False)
    op.create_index(
        "welder_ident_idx", "welder_table", ["ident"], unique=False
    )
    op.create_index(
        "welder_kleymo_idx", "welder_table", ["kleymo"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("welder_kleymo_idx", table_name="welder_table")
    op.drop_index("welder_ident_idx", table_name="welder_table")
    op.drop_index("name_idx", table_name="welder_table")
    op.drop_constraint(None, "welder_certification_table", type_="unique")
    op.drop_index(
        "welder_certification_kleymo_idx",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "welder_certification_ident_idx",
        table_name="welder_certification_table",
    )
    op.drop_index(
        "rod_diameter_from_idx", table_name="welder_certification_table"
    )
    op.drop_index(
        "rod_diameter_before_idx", table_name="welder_certification_table"
    )
    op.drop_index(
        "outer_diameter_from_idx", table_name="welder_certification_table"
    )
    op.drop_index(
        "outer_diameter_before_idx", table_name="welder_certification_table"
    )
    op.drop_index("method_idx", table_name="welder_certification_table")
    op.drop_index("gtd_idx", table_name="welder_certification_table")
    op.drop_index(
        "details_thikness_from_idx", table_name="welder_certification_table"
    )
    op.drop_index(
        "details_thikness_before_idx", table_name="welder_certification_table"
    )
    op.drop_index("certification_idx", table_name="welder_certification_table")
    op.drop_index("user_ident_idx", table_name="user_table")
    op.drop_index("token_idx", table_name="refresh_token_table")
    op.drop_index("revoked_idx", table_name="refresh_token_table")
    op.drop_index("refresh_token_ident_idx", table_name="refresh_token_table")
    op.drop_constraint(None, "ndt_table", type_="unique")
    op.drop_index("total_welded_idx", table_name="ndt_table")
    op.drop_index("total_ndt_idx", table_name="ndt_table")
    op.drop_index("rejected_idx", table_name="ndt_table")
    op.drop_index("ndt_idx", table_name="ndt_table")
    op.drop_index("ndt_ident_idx", table_name="ndt_table")
    op.drop_index("accepted_idx", table_name="ndt_table")
    # ### end Alembic commands ###
